version: '3.9'

services:
  postgres:
    image: postgres:17.3
    container_name: postgres_sokoban_java
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sokoban
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
        driver: local